fix: update method to calculate span url
Byndyusoft/nest-opentracing pull request #23
Opened 2022-02-20 14:46 UTC by meerfolk

2022-02-21 05:38 UTC, KillWolfVlad requested changes

2022-02-21 05:38 UTC, KillWolfVlad commented on src/clients/http/helpers/getFullUrl.ts
> +export function getFullUrl(baseUrl: string, url: string): string {
Why not use https://www.npmjs.com/package/url-join?

2022-02-22 11:06 UTC, KillWolfVlad requested changes

2022-02-22 11:06 UTC, KillWolfVlad commented on src/clients/http/helpers/getFullUrl.ts
> +
We can call `url-join` without directly, without helper.

2022-03-23 12:48 UTC, zeleebobo approved these changes

2022-03-23 12:51 UTC, KillWolfVlad approved these changes

2022-03-23 12:53 UTC, merged